# Generated by Django 5.2.8 on 2025-11-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garages/'),
        ),
    ]
