# Generated by Django 5.2.8 on 2025-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_garage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageservice',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
