# Generated by Django 5.2.8 on 2025-11-10 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_alter_garageservice_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='garage',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
