# Generated by Django 5.2.8 on 2025-11-10 07:49
# Generated by Django 5.2.4 on 2025-11-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            # field=models.CharField(default='TEMP', editable=False, max_length=15, unique=True),
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='delivery_option',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Self-Drop', 'Self-Drop')], default='Self-Drop', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='bookings.booking')),
            ],
        ),
    ]
