# Generated by Django 5.2.8 on 2025-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_vehicle'),
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='garage.garageservice'),
        ),
    ]
