# Generated by Django 5.2.8 on 2025-11-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
    ]
