# Generated by Django 6.0 on 2025-12-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_expires_at',
        ),
    ]
